### PR TITLE
testing:test.html

### PR DESCRIPTION
**Pull request by Shreya-Jayaraj**
This repo includes the implementation of SVM model for Spam detection.

### CODE REVIEW

**Comment by Shreya-Jayaraj** [comment]
@Clasherzz this repo is ready for review

**Comment by Clasherzz** [comment]
Thanks for the support .

**Comment by Shreya-Jayaraj** [comment]
@Clasherzz this repo is ready to merge

**Comment by Clasherzz** [comment]
LGTM

**Pull request merged**
